// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP2_SD.Database;

namespace TP2_SD.Migrations
{
    [DbContext(typeof(ChavesContext))]
    partial class ChavesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TP2_SD.Models.RegistoAposta", b =>
                {
                    b.Property<int>("RegistoApostaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Arquivada")
                        .HasColumnType("bit");

                    b.Property<int?>("ChaveId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("NIF")
                        .HasColumnType("int");

                    b.Property<int>("Premio")
                        .HasColumnType("int");

                    b.HasKey("RegistoApostaId");

                    b.HasIndex("ChaveId");

                    b.ToTable("Apostas");
                });

            modelBuilder.Entity("TP2_SD.Models.RegistoChave", b =>
                {
                    b.Property<int>("ChaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Estrelas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numeros")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChaveId");

                    b.ToTable("Chaves");
                });

            modelBuilder.Entity("TP2_SD.Models.RegistoAposta", b =>
                {
                    b.HasOne("TP2_SD.Models.RegistoChave", "Chave")
                        .WithMany()
                        .HasForeignKey("ChaveId");

                    b.Navigation("Chave");
                });
#pragma warning restore 612, 618
        }
    }
}
